# ============================================================
# gemini_rbi_answer_generation.py
#
# RBI RAG — ANSWER GENERATION PIPELINE USING GOOGLE GEMINI
#
# Key Features:
# 1. Uses Google Gemini (gemini-2.5-flash) exclusively for generation.
# 2. Multi-key failover: reads "gemini_keys" from openrouter_keys.json.
#    If key 1 fails (rate limit, timeout, error), it fails over
#    immediately to key 2, key 3, etc.
# 3. Checkpointed / Resumable: saves response_generated.json atomically
#    after EVERY single question.
# 4. Preserves full context: top-5 chunks (approx 2800-3300 tokens)
#    are delivered intact to Gemini's 1M+ token context window.
# 5. Strict schema matching: downstream evaluation pipelines can read
#    response_generated.json without any structural changes.
# ============================================================

import os
import json
import time
from pathlib import Path

import faiss
from dotenv import load_dotenv
from openai import OpenAI
from sentence_transformers import SentenceTransformer


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent


# ============================================================
# FILES / DIRECTORIES
# ============================================================

# Output generated by the token-based chunking/indexing pipeline.
OUTPUT_DIR = BASE_DIR / "output_chunks_16_09_v3"

FAISS_INDEX_PATH = OUTPUT_DIR / "rbi_chunks.index"
CHUNK_META_PATH = OUTPUT_DIR / "rbi_chunk_metadata.json"

# Complete question bank.
TEST_FILE = BASE_DIR / "test_file.json"

# Checkpoint/output file.
# This file is updated AFTER EVERY QUESTION.
GENERATION_OUTPUT_FILE = BASE_DIR / "gemini_response_generated.json"

# Optional local BGE-M3 directory.
LOCAL_BGE_MODEL_PATH = os.getenv(
    "BGE_MODEL_PATH",
    str(BASE_DIR.parent / "models" / "bge-m3")
)


# ============================================================
# MODEL CONFIGURATION
# ============================================================

EMBEDDING_MODEL = "BAAI/bge-m3"

# Gemini answer-generation model.
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

# Google OpenAI-compatible endpoint.
GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai/"

DEFAULT_TOP_K = 5

# Maximum OUTPUT tokens generated for one answer.
# Set to 500 to account for internal model thinking tokens and full citations.
MAX_OUTPUT_TOKENS = int(os.getenv("MAX_OUTPUT_TOKENS", "500"))

TEMPERATURE = 0

# Maximum time allowed for a Gemini request.
GEMINI_TIMEOUT = float(os.getenv("GEMINI_TIMEOUT", "60"))

# Maximum questions to process (default: 30 for testing, unset or 0 for all)
_max_q_env = os.getenv("RAG_MAX_QUESTIONS", "30")
MAX_QUESTIONS = int(_max_q_env) if _max_q_env and int(_max_q_env) > 0 else None


# ============================================================
# GEMINI MULTIPLE KEYS LOADER
# ============================================================
# openrouter_keys.json:
#
# {
#   "keys": [ ... ],
#   "gemini_keys": [
#       "AIzaSyKey1...",
#       "AIzaSyKey2...",
#       "AIzaSyKey3..."
#   ]
# }
#
# Keys are tried in order.
# A failed key is followed immediately by the next key.

OPENROUTER_KEYS_FILE = BASE_DIR / "openrouter_keys.json"


def load_gemini_keys():
    """Load all valid Google Gemini API keys from openrouter_keys.json."""

    keys = []

    if OPENROUTER_KEYS_FILE.exists():
        try:
            with open(OPENROUTER_KEYS_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)

            raw_keys = data.get("gemini_keys", [])
            if isinstance(raw_keys, list):
                keys = [
                    k.strip()
                    for k in raw_keys
                    if isinstance(k, str) and k.strip()
                ]
        except Exception as e:
            print(f"Warning: Could not parse {OPENROUTER_KEYS_FILE}: {e}")

    # Fallback to GEMINI_API_KEY in .env if no keys found in JSON
    env_key = os.getenv("GEMINI_API_KEY")
    if env_key and env_key.strip() and env_key.strip() not in keys:
        keys.append(env_key.strip())

    if not keys:
        raise ValueError(
            f"No valid Gemini API keys found in {OPENROUTER_KEYS_FILE} "
            "under 'gemini_keys' or in environment variable GEMINI_API_KEY."
        )

    print(f"Loaded {len(keys)} Gemini API keys for multi-key failover.")
    return keys


GEMINI_KEYS = load_gemini_keys()


# ============================================================
# ATOMIC JSON CHECKPOINT
# ============================================================

def save_json_checkpoint(data):
    """Atomically write data to temporary file and replace target."""
    temp_file = GENERATION_OUTPUT_FILE.with_suffix(".tmp.json")

    with open(temp_file, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    os.replace(temp_file, GENERATION_OUTPUT_FILE)


# ============================================================
# LOAD PREVIOUS CHECKPOINT
# ============================================================

def load_previous_results():
    """Load previous checkpoint to allow resuming uninterrupted."""
    if not GENERATION_OUTPUT_FILE.exists():
        return []

    try:
        with open(GENERATION_OUTPUT_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)

        if not isinstance(data, list):
            print("Existing response_generated.json is not a list. Starting fresh.")
            return []

        return data

    except Exception as e:
        print(f"Could not read existing checkpoint: {e}")
        print("Starting with an empty result set.")
        return []


# ============================================================
# LOAD RAG RESOURCES
# ============================================================

def load_rag_resources():
    print("=" * 70)
    print("LOADING RAG RESOURCES")
    print("=" * 70)

    # ----------------------------
    # FAISS Index
    # ----------------------------
    if not FAISS_INDEX_PATH.exists():
        raise FileNotFoundError(f"FAISS index not found:\n{FAISS_INDEX_PATH}")

    print(f"Loading FAISS index:\n{FAISS_INDEX_PATH}")
    index = faiss.read_index(str(FAISS_INDEX_PATH))
    print(f"FAISS vectors loaded: {index.ntotal}")

    # ----------------------------
    # Chunk Metadata
    # ----------------------------
    if not CHUNK_META_PATH.exists():
        raise FileNotFoundError(f"Chunk metadata not found:\n{CHUNK_META_PATH}")

    print(f"Loading chunk metadata:\n{CHUNK_META_PATH}")
    with open(CHUNK_META_PATH, "r", encoding="utf-8") as f:
        chunks = json.load(f)
    print(f"Chunk metadata entries: {len(chunks)}")

    # ----------------------------
    # BGE-M3 Embedding Model
    # ----------------------------
    local_model_path = Path(LOCAL_BGE_MODEL_PATH).expanduser()

    if local_model_path.is_dir():
        print(f"Loading BGE-M3 from local directory:\n{local_model_path}")
        embedding_model = SentenceTransformer(str(local_model_path))
    else:
        print(f"Local BGE-M3 path not found. Loading model via name: {EMBEDDING_MODEL}")
        embedding_model = SentenceTransformer(EMBEDDING_MODEL)

    print("Embedding model loaded successfully.")
    return index, chunks, embedding_model


# ============================================================
# LOAD TEST DATA
# ============================================================

def load_test_data():
    """Load test dataset from test.json."""
    if not TEST_FILE.exists():
        raise FileNotFoundError(f"test.json not found:\n{TEST_FILE}")

    with open(TEST_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, list):
        questions = data
    elif isinstance(data, dict):
        if "questions" in data and isinstance(data["questions"], list):
            questions = data["questions"]
        elif "question" in data:
            questions = [data]
        else:
            raise ValueError("test.json dictionary must contain 'questions' or 'question'.")
    else:
        raise ValueError("Invalid test.json format.")

    return questions


# ============================================================
# RETRIEVAL
# ============================================================

def retrieve_chunks(query, index, chunks, embedding_model, top_k=DEFAULT_TOP_K):
    """Retrieve top-K most relevant chunks using cosine similarity."""
    retrieval_start = time.perf_counter()

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")

    distances, indices = index.search(query_embedding, top_k)

    results = []
    for rank, (distance, idx) in enumerate(zip(distances[0], indices[0]), start=1):
        if idx < 0 or idx >= len(chunks):
            continue

        chunk = chunks[idx]
        results.append({
            "rank": rank,
            "distance": float(distance),
            "chunk_id": chunk.get("chunk_id"),
            "source_file": chunk.get("source_file"),
            "chunk_number": chunk.get("chunk_number"),
            "chunk_text": chunk.get("chunk_text", ""),
            "char_count": chunk.get("char_count"),
            "token_count": chunk.get("token_count")
        })

    retrieval_time = time.perf_counter() - retrieval_start
    return results, retrieval_time


# ============================================================
# BUILD CONTEXT
# ============================================================

def build_context(retrieved_chunks):
    """Assemble context blocks from retrieved chunks."""
    context_parts = []
    for result in retrieved_chunks:
        context_parts.append(
            f"Source file: {result.get('source_file')}\n"
            f"Chunk number: {result.get('chunk_number')}\n"
            f"Chunk ID: {result.get('chunk_id')}\n"
            f"Content:\n{result.get('chunk_text', '')}"
        )
    return "\n\n---\n\n".join(context_parts)


# ============================================================
# TOKEN USAGE EXTRACTION
# ============================================================

def extract_token_usage(response):
    """Extract token usage metrics from Gemini response."""
    usage = getattr(response, "usage", None)
    if usage is None:
        return {"input_tokens": None, "output_tokens": None, "total_tokens": None}

    input_tokens = getattr(usage, "prompt_tokens", None) or getattr(usage, "input_tokens", None)
    output_tokens = getattr(usage, "completion_tokens", None) or getattr(usage, "output_tokens", None)
    total_tokens = getattr(usage, "total_tokens", None)

    if total_tokens is None and input_tokens is not None and output_tokens is not None:
        total_tokens = input_tokens + output_tokens

    return {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": total_tokens
    }


# ============================================================
# GENERATE ANSWER WITH MULTI-KEY FAILOVER
# ============================================================

def generate_answer(query, retrieved_chunks):
    """
    Generate one answer using Google Gemini.
    Tries each Gemini API key sequentially if a failure occurs.
    """
    generation_start = time.perf_counter()
    context = build_context(retrieved_chunks)

    system_prompt = """
You are an RBI document question-answering assistant.

Your task is to answer the user's question using ONLY the
retrieved RBI document context provided to you.

Follow these rules strictly:

1. Use only information present in the retrieved context.
2. Do not use outside knowledge.
3. Do not invent or assume information.
4. If the answer is not available in the retrieved context,
   say that the answer is not available in the retrieved documents.
5. Give a direct and complete answer to the user's question.
6. Preserve exact RBI terminology, names, dates, numbers,
   circular numbers, codes, and monetary values.
7. If the answer is present in a table, use the table values.
8. Do not mention information that is not supported by the context.

9. Always provide the complete answer FIRST.

10. After the complete answer, provide the source information
    separately.

11. The source information must appear AFTER the answer and
    must include the source file and chunk number when available.
    Include the paragraph/reference number when it is available
    in the retrieved context.

12. Do not place the source information before the answer.

Use the following format:

Answer:
[Complete answer to the user's question]

Source:
Source File: [source file]
Chunk: [chunk number]
Paragraph/Reference: [paragraph or reference, if available]
"""

    user_prompt = f"""
Retrieved RBI document context:

{context}

User question:

{query}

Provide the answer based only on the retrieved context.
"""

    key_attempt_errors = []

    # --------------------------------------------------------
    # TRY ALL GEMINI KEYS
    # --------------------------------------------------------
    for key_number, api_key in enumerate(GEMINI_KEYS, start=1):
        try:
            print(f"  Trying Gemini key {key_number}/{len(GEMINI_KEYS)}...")

            client = OpenAI(
                api_key=api_key,
                base_url=GEMINI_BASE_URL,
                timeout=GEMINI_TIMEOUT,
                max_retries=0
            )

            response = client.chat.completions.create(
                model=GEMINI_MODEL,
                max_tokens=MAX_OUTPUT_TOKENS,
                temperature=TEMPERATURE,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ]
            )

            answer = response.choices[0].message.content or ""
            generation_time = time.perf_counter() - generation_start

            return {
                "generated_answer": answer,
                "provider": "Gemini",
                "model": GEMINI_MODEL,
                "gemini_key_number": key_number,
                "generation_time_seconds": generation_time,
                **extract_token_usage(response),
                "generation_success": True,
                "generation_error": None,
                "key_attempt_errors": key_attempt_errors
            }

        except Exception as e:
            error_text = f"{type(e).__name__}: {e}"
            print(f"  Key {key_number} failed: {error_text}")

            key_attempt_errors.append({
                "key_number": key_number,
                "error": error_text
            })

            # Immediately fail over to the next key
            continue

    # --------------------------------------------------------
    # ALL KEYS FAILED
    # --------------------------------------------------------
    generation_time = time.perf_counter() - generation_start

    return {
        "generated_answer": "",
        "provider": "Gemini",
        "model": GEMINI_MODEL,
        "gemini_key_number": None,
        "generation_time_seconds": generation_time,
        "input_tokens": None,
        "output_tokens": None,
        "total_tokens": None,
        "generation_success": False,
        "generation_error": "All Gemini API keys failed.",
        "key_attempt_errors": key_attempt_errors
    }


# ============================================================
# PROCESS ONE QUESTION
# ============================================================

def process_question(question_number, test_item, index, chunks, embedding_model):
    """Retrieve, generate and return one complete result record."""
    question_start = time.perf_counter()

    question = str(test_item.get("question", "")).strip()
    question_id = f"Q{question_number:04d}"

    # --------------------------------------------------------
    # EMPTY QUESTION CHECK
    # --------------------------------------------------------
    if not question:
        return {
            "question_id": question_id,
            "question_number": question_number,
            "question": "",
            "generated_answer": "",
            "provider": None,
            "model": None,
            "gemini_key_number": None,
            "ground_truth": test_item.get("ground_truth"),
            "ground_truth_reference": test_item.get("ground_truth_reference"),
            "difficulty": test_item.get("difficulty"),
            "fetched_chunks": [],
            "sources_answered": [],
            "retrieval_time_seconds": 0,
            "generation_time_seconds": 0,
            "total_question_time_seconds": time.perf_counter() - question_start,
            "input_tokens": None,
            "output_tokens": None,
            "total_tokens": None,
            "generation_success": False,
            "generation_status": "SKIPPED",
            "generation_error": "EMPTY_QUESTION",
            "evaluation_status": "NOT_EVALUATED",
            "evaluation_reason": "EMPTY_QUESTION",
            "key_attempt_errors": []
        }

    # --------------------------------------------------------
    # RETRIEVAL PHASE
    # --------------------------------------------------------
    try:
        fetched_chunks, retrieval_time = retrieve_chunks(
            question,
            index,
            chunks,
            embedding_model,
            DEFAULT_TOP_K
        )
    except Exception as e:
        error_text = f"{type(e).__name__}: {e}"
        return {
            "question_id": question_id,
            "question_number": question_number,
            "question": question,
            "generated_answer": "",
            "provider": None,
            "model": None,
            "gemini_key_number": None,
            "ground_truth": test_item.get("ground_truth"),
            "ground_truth_reference": test_item.get("ground_truth_reference"),
            "difficulty": test_item.get("difficulty"),
            "fetched_chunks": [],
            "sources_answered": [],
            "retrieval_time_seconds": None,
            "generation_time_seconds": None,
            "total_question_time_seconds": time.perf_counter() - question_start,
            "input_tokens": None,
            "output_tokens": None,
            "total_tokens": None,
            "generation_success": False,
            "generation_status": "FAILED",
            "generation_error": None,
            "retrieval_error": error_text,
            "evaluation_status": "NOT_EVALUATED",
            "evaluation_reason": "RETRIEVAL_FAILED",
            "key_attempt_errors": []
        }

    # --------------------------------------------------------
    # GENERATION PHASE
    # --------------------------------------------------------
    generation_result = generate_answer(question, fetched_chunks)

    # --------------------------------------------------------
    # SOURCE EXTRACTION
    # --------------------------------------------------------
    sources_answered = [
        {
            "source_file": chunk.get("source_file"),
            "chunk_number": chunk.get("chunk_number"),
            "chunk_id": chunk.get("chunk_id"),
            "rank": chunk.get("rank"),
            "distance": chunk.get("distance")
        }
        for chunk in fetched_chunks
    ]

    # --------------------------------------------------------
    # STATUS DETERMINATION
    # --------------------------------------------------------
    if generation_result["generation_success"]:
        generation_status = "SUCCESS"
        evaluation_status = "PENDING"
        evaluation_reason = None
    else:
        generation_status = "FAILED"
        evaluation_status = "NOT_EVALUATED"
        evaluation_reason = "GENERATION_FAILED"

    return {
        "question_id": question_id,
        "question_number": question_number,
        "question": question,
        "generated_answer": generation_result["generated_answer"],
        "provider": generation_result["provider"],
        "model": generation_result["model"],
        "gemini_key_number": generation_result["gemini_key_number"],
        "ground_truth": test_item.get("ground_truth"),
        "ground_truth_reference": test_item.get("ground_truth_reference"),
        "difficulty": test_item.get("difficulty"),
        "fetched_chunks": fetched_chunks,
        "sources_answered": sources_answered,
        "retrieval_time_seconds": retrieval_time,
        "generation_time_seconds": generation_result["generation_time_seconds"],
        "total_question_time_seconds": time.perf_counter() - question_start,
        "input_tokens": generation_result["input_tokens"],
        "output_tokens": generation_result["output_tokens"],
        "total_tokens": generation_result["total_tokens"],
        "generation_success": generation_result["generation_success"],
        "generation_status": generation_status,
        "generation_error": generation_result["generation_error"],
        "evaluation_status": evaluation_status,
        "evaluation_reason": evaluation_reason,
        "key_attempt_errors": generation_result["key_attempt_errors"]
    }


# ============================================================
# MAIN PIPELINE
# ============================================================

def main():
    print()
    print("=" * 70)
    print("RBI RAG — GENERATION PIPELINE (GOOGLE GEMINI MULTI-KEY)")
    print("=" * 70)
    print(f"Active Model  : {GEMINI_MODEL}")
    print(f"API Endpoint  : {GEMINI_BASE_URL}")
    print(f"Keys Config   : {len(GEMINI_KEYS)} keys loaded")

    # --------------------------------------------------------
    # 1. LOAD RAG RESOURCES
    # --------------------------------------------------------
    index, chunks, embedding_model = load_rag_resources()

    # --------------------------------------------------------
    # 2. LOAD TEST QUESTIONS
    # --------------------------------------------------------
    all_questions = load_test_data()
    if MAX_QUESTIONS is not None and MAX_QUESTIONS > 0:
        questions = all_questions[:MAX_QUESTIONS]
        print(f"Processing first {len(questions)} questions (RAG_MAX_QUESTIONS={MAX_QUESTIONS}).")
    else:
        questions = all_questions
        print(f"Processing full dataset of {len(questions)} questions.")

    # --------------------------------------------------------
    # 3. LOAD EXISTING CHECKPOINT
    # --------------------------------------------------------
    existing_results = load_previous_results()

    completed = {
        result.get("question_id"): result
        for result in existing_results
        if result.get("question_id") and result.get("generation_success") is True
    }

    print(f"Previously completed questions: {len(completed)}")

    results_by_id = {
        result.get("question_id"): result
        for result in existing_results
        if result.get("question_id")
    }

    # --------------------------------------------------------
    # 4. PROCESS QUESTIONS WITH RESUME
    # --------------------------------------------------------
    for question_number, test_item in enumerate(questions, start=1):
        question_id = f"Q{question_number:04d}"

        print()
        print("-" * 70)
        print(f"QUESTION {question_number}/{len(questions)} ({question_id})")
        print(test_item.get("question", ""))

        if question_id in completed:
            print("Already generated successfully. Skipping API call.")
            continue

        result = process_question(
            question_number,
            test_item,
            index,
            chunks,
            embedding_model
        )

        results_by_id[question_id] = result

        # Rebuild ordered results list
        ordered_results = []
        for number in range(1, len(questions) + 1):
            qid = f"Q{number:04d}"
            if qid in results_by_id:
                ordered_results.append(results_by_id[qid])

        save_json_checkpoint(ordered_results)
        print(f"Checkpoint saved after question {question_number}.")

        if result.get("generation_success"):
            print("Generation: SUCCESS")
            print(f"Gemini key   : {result.get('gemini_key_number')}")
            print(f"Input tokens : {result.get('input_tokens')}")
            print(f"Output tokens: {result.get('output_tokens')}")
            print(f"Total tokens : {result.get('total_tokens')}")
            print(f"Latency      : {result.get('generation_time_seconds'):.2f}s")
        else:
            print("Generation: FAILED")
            failure_reason = (
                result.get("generation_error")
                or result.get("retrieval_error")
                or "UNKNOWN_ERROR"
            )
            print(f"Reason: {failure_reason}")

    # --------------------------------------------------------
    # 5. FINAL SUMMARY
    # --------------------------------------------------------
    final_results = []
    for number in range(1, len(questions) + 1):
        qid = f"Q{number:04d}"
        if qid in results_by_id:
            final_results.append(results_by_id[qid])

    save_json_checkpoint(final_results)

    success_count = sum(
        1 for r in final_results if r.get("generation_success") is True
    )
    failed_count = len(final_results) - success_count

    print()
    print("=" * 70)
    print("GENERATION RUN COMPLETE")
    print("=" * 70)
    print(f"Total questions processed/saved : {len(final_results)}")
    print(f"Successful generations          : {success_count}")
    print(f"Failed/skipped generations      : {failed_count}")
    print(f"Output checkpoint file          : {GENERATION_OUTPUT_FILE}")
    print()


if __name__ == "__main__":
    main()
